[package]
name = "prismswap"
version = "1.0.1"
edition = "2018"
license = "Apache-2.0"
description = "Common helpers for PrismSwap"

[dependencies]
cw20 = { version = "0.8" }
terra-cosmwasm = { version = "2.2.0" }
cosmwasm-std = { version = "0.16.0", default-features = false }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
cw-asset = "0.3.4"